using Polkadot.BinarySerializer;
using Polkadot.BinarySerializer.Converters;

namespace Polkadot.Api.Client.Model.DigestItemValues
{
    /// A message from the runtime to the consensus engine. This should *never*
    /// be generated by the native code of any consensus engine, but this is not
    /// checked (yet).
    public class Consensus
    {
        [Serialize(0)]
        public ConsensusEngineId Id { get; set; }

        [Serialize(1)]
        [PrefixedArrayConverter]
        public byte[] Something { get; set; }
    }
}